/**
 * Dumping the schema, and generating types from it.
 *
 * Rails writes `schema.rb` and loads it to prepare a test database rather than
 * replaying every migration. This writes the same two things, plus one Rails
 * cannot: TypeScript interfaces for every table, so a model's attributes come
 * from the database rather than from someone remembering to update them.
 *
 * That is the whole point. A column added in a migration and forgotten in an
 * interface is currently a silent lie — the compiler confidently reports a
 * shape the database does not have. After this, it is a type error.
 */

import { classify, singularize } from "@altair/support";
import type { Connection } from "./connection.js";
import type { ColumnSchema, SchemaDefinition, TableSchema } from "./introspect.js";
import { SchemaStatements, type ColumnType } from "./schema.js";

const GENERATED_HEADER = (
  kind: string,
) => `// GENERATED by \`altair db:migrate\` — do not edit by hand.
//
// ${kind}
// Regenerate: altair db:schema:dump
`;

/**
 * Maps a database type to one of the migration DSL's types.
 *
 * Adapters spell the same type several ways — SQLite reports VARCHAR(255),
 * Postgres character varying, MySQL varchar — so this normalizes rather than
 * matching exactly.
 */
export function columnTypeFor(databaseType: string): ColumnType {
  const type = databaseType.toLowerCase();

  if (type.includes("int")) return type.includes("big") ? "bigint" : "integer";
  if (type.includes("char") || type.includes("varying")) return "string";
  if (type.includes("text")) return "text";
  if (type.includes("bool")) return "boolean";
  if (type.includes("json")) return "json";
  if (type.includes("blob") || type.includes("bytea") || type.includes("binary")) return "binary";
  if (type.includes("decimal") || type.includes("numeric")) return "decimal";
  if (type.includes("double") || type.includes("real") || type.includes("float")) return "float";
  if (type.includes("timestamp") || type.includes("datetime")) return "datetime";
  if (type.includes("date")) return "date";

  return "string";
}

/**
 * The TypeScript type a column's values arrive as.
 *
 * These describe what a driver actually returns, not what the column means. A
 * SQLite boolean comes back as 0 or 1 and a timestamp as a string, and saying
 * otherwise would make the generated type wrong in the same way a hand-written
 * one is.
 */
export function tsTypeFor(column: ColumnSchema): string {
  const type = columnTypeFor(column.type);

  switch (type) {
    case "integer":
    case "bigint":
    case "float":
    case "decimal":
      return "number";
    case "boolean":
      // Stored as 0/1 by SQLite and MySQL; only Postgres has a real boolean.
      return "number | boolean";
    case "json":
      return "unknown";
    case "binary":
      return "Uint8Array";
    default:
      return "string";
  }
}

/** The interface name for a table: `posts` becomes `PostRow`. */
export function rowTypeName(table: string): string {
  return `${classify(singularize(table))}Row`;
}

/** Emits the schema as a loadable definition. Our `schema.rb`. */
export function dumpSchema(schema: SchemaDefinition): string {
  const tables = schema.tables
    .map((table) => {
      const columns = table.columns
        .map(
          (column) =>
            `        { name: ${JSON.stringify(column.name)}, type: ${JSON.stringify(column.type)}, nullable: ${column.nullable}, default: ${JSON.stringify(column.default)}, primaryKey: ${column.primaryKey} },`,
        )
        .join("\n");

      const indexes = table.indexes
        .map(
          (index) =>
            `        { name: ${JSON.stringify(index.name)}, columns: ${JSON.stringify(index.columns)}, unique: ${index.unique} },`,
        )
        .join("\n");

      return `    {
      name: ${JSON.stringify(table.name)},
      columns: [
${columns}
      ],
      indexes: [
${indexes}
      ],
    },`;
    })
    .join("\n");

  return `${GENERATED_HEADER("The database's current shape, as of the migration named by `version`.")}
import type { SchemaDefinition } from "@altair/orm";

const schema: SchemaDefinition = {
  version: ${JSON.stringify(schema.version)},
  tables: [
${tables}
  ],
};

export default schema;
`;
}

/** Emits an interface per table, for models to use as their attributes. */
export function dumpTypes(schema: SchemaDefinition): string {
  const interfaces = schema.tables
    .map((table) => {
      const fields = table.columns
        .map((column) => {
          const type = tsTypeFor(column);
          const nullable = column.nullable ? " | null" : "";
          return `  ${isSafeIdentifier(column.name) ? column.name : JSON.stringify(column.name)}: ${type}${nullable};`;
        })
        .join("\n");

      return `/** Rows of the \`${table.name}\` table. */
export interface ${rowTypeName(table.name)} {
${fields}
}`;
    })
    .join("\n\n");

  const map = schema.tables
    .map((table) => `  ${JSON.stringify(table.name)}: ${rowTypeName(table.name)};`)
    .join("\n");

  return `${GENERATED_HEADER("Attribute types for every table, read from the database itself.")}
${interfaces}

/** Every table, keyed by name. Useful for generic code over the schema. */
export interface Tables {
${map}
}
`;
}

function isSafeIdentifier(name: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

/**
 * Creates every table in a definition.
 *
 * Rails prepares a test database by loading `schema.rb` rather than replaying
 * every migration, which is the difference between a test suite that starts in
 * milliseconds and one that starts in seconds.
 */
export async function loadSchema(connection: Connection, schema: SchemaDefinition): Promise<void> {
  const statements = new SchemaStatements(connection);

  for (const table of schema.tables) {
    await createFromDefinition(statements, table);
  }

  // The version is recorded so a loaded database does not look unmigrated.
  await connection.execute(
    `CREATE TABLE IF NOT EXISTS ${connection.quote("schema_migrations")} (${connection.quote("version")} VARCHAR(255) NOT NULL PRIMARY KEY)`,
  );

  if (schema.version) {
    await connection.execute(
      `INSERT INTO ${connection.quote("schema_migrations")} (${connection.quote("version")}) VALUES (${connection.placeholder(0)})`,
      [schema.version],
    );
  }
}

async function createFromDefinition(
  statements: SchemaStatements,
  table: TableSchema,
): Promise<void> {
  const primaryKey = table.columns.find((column) => column.primaryKey);

  await statements.createTable(
    table.name,
    (definition) => {
      for (const column of table.columns) {
        if (column.primaryKey) continue;

        definition.column(column.name, columnTypeFor(column.type), {
          null: column.nullable,
          ...(column.default === null ? {} : { default: column.default }),
        });
      }
    },
    // A table whose primary key the dump did not find is recreated without one,
    // rather than being given an id it never had.
    { id: primaryKey !== undefined, ifNotExists: true },
  );

  for (const index of table.indexes) {
    await statements.addIndex(table.name, index.columns, {
      name: index.name,
      unique: index.unique,
    });
  }
}
