/**
 * Generating typed path helpers from the route table.
 *
 * Rails defines `edit_post_path` at boot by metaprogramming, which no type
 * checker can see: the name exists, its arity does not, and a missing argument
 * is a 404 in production rather than an error in the editor.
 *
 * The same answer as the schema dump: read the real thing and emit types from
 * it. The route table knows every route's name and exactly which segments it
 * requires, so the generated helper takes those and nothing else.
 */

import type { Route } from "./route.js";
import { helperName, type Router } from "./router.js";

const HEADER = `// GENERATED by \`altair routes:types\` — do not edit by hand.
//
// A typed path helper per named route, built from the route table itself.
// Regenerate after changing config/routes.
`;

/** A segment value: an id, or a record that knows its own. */
const PARAM_TYPE = "ParamValue";

/** Anything left over becomes a query string, as it does in Rails. */
const QUERY_TYPE = "QueryParams";

const PREAMBLE = `/** A segment value: an id, or a record that knows its own. */
export type ParamValue = string | number | { toParam(): unknown } | { id: unknown };

/** Anything not consumed by a segment becomes a query string, as in Rails. */
export type QueryParams = Record<string, unknown>;`;

/** The segments a helper has to be given, `format` aside. */
export function requiredSegments(route: Route): string[] {
  return route.requiredParams.filter((param) => param !== "format");
}

/** The TypeScript signature for one route's helper. */
export function helperSignature(route: Route, name: string): string {
  const segments = requiredSegments(route);
  const parameters = segments.map((segment) => `${camel(segment)}: ${PARAM_TYPE}`);
  parameters.push(`query?: ${QUERY_TYPE}`);

  return `  /** \`${route.method} ${route.pattern}\` */\n  ${name}(${parameters.join(", ")}): string;`;
}

function camel(value: string): string {
  return value.replace(/_([a-z])/g, (_, letter: string) => letter.toUpperCase());
}

/**
 * Emits a module of typed path helpers.
 *
 * The helpers are named exports rather than one object, so an editor completes
 * them from a bare import and a bundler can drop the ones a page never calls.
 */
export function dumpRouteHelpers(router: Router, options: { routesModule?: string } = {}): string {
  const module = options.routesModule ?? "./routes.js";

  const entries: { name: string; route: Route }[] = [];
  for (const routeName of router.routeNames) {
    const route = router.routeNamed(routeName);
    if (route) entries.push({ name: helperName(routeName), route });
  }

  const declarations = entries.map(({ name, route }) => helperSignature(route, name)).join("\n\n");

  const exports = entries
    .map(
      ({ name }) =>
        `export const ${name} = helpers.${name} as PathHelpers[${JSON.stringify(name)}];`,
    )
    .join("\n");

  return `${HEADER}
import { router } from ${JSON.stringify(module)};

${PREAMBLE}

export interface PathHelpers {
${declarations}
}

const helpers = router.pathHelpers() as unknown as PathHelpers;

/** Every helper, for code that wants them as one object. */
export const paths: PathHelpers = helpers;

${exports}
`;
}
