/**
 * Ports Rails' canonical inflector fixtures into TypeScript.
 *
 * The point of this script is that our test data is *derived from Rails*, not
 * invented by us. When Rails updates its fixtures, re-run this and the diff
 * shows exactly what changed.
 *
 *   bun run tools/port-fixtures.ts [path-to-rails-clone]
 *
 * Default clone path: ../research/rails (a sibling of the repo, so the 61 MB
 * clone never lands inside our history).
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const railsRoot = process.argv[2] ?? join(process.cwd(), "..", "research", "rails");
const source = join(
  railsRoot,
  "activesupport",
  "test",
  "inflector_test_cases.rb",
);

if (!existsSync(source)) {
  console.error(`Rails clone not found at ${railsRoot}`);
  console.error(
    "Clone it first:  git clone --depth 1 https://github.com/rails/rails ../research/rails",
  );
  process.exit(1);
}

const ruby = readFileSync(source, "utf8");

/** `Name = { "a" => "b", ... }` blocks, plus the array-shaped ones. */
function hashBlocks(src: string): Map<string, [string, string][]> {
  const out = new Map<string, [string, string][]>();
  for (const block of src.matchAll(/^\s*(\w+) = \{([\s\S]*?)^\s*\}/gm)) {
    const name = block[1]!;
    const body = block[2]!;
    const pairs = [...body.matchAll(/"((?:[^"\\]|\\.)*)"\s*=>\s*"((?:[^"\\]|\\.)*)"/g)]
      .map((m) => [unescapeRuby(m[1]!), unescapeRuby(m[2]!)] as [string, string]);
    if (pairs.length > 0) out.set(name, pairs);
  }
  return out;
}

/**
 * Ruby string escapes that appear in the fixture file. The octal form matters:
 * Rails uses "\251" to build a deliberately malformed-UTF-8 parameterize case,
 * and leaving it as a literal backslash would change what the test asserts.
 */
function unescapeRuby(s: string): string {
  return s
    .replace(/\\([0-7]{1,3})/g, (_, oct) => String.fromCharCode(parseInt(oct, 8)))
    .replace(/\\x([0-9a-fA-F]{2})/g, (_, hex) => String.fromCharCode(parseInt(hex, 16)))
    .replace(/\\u\{([0-9a-fA-F]+)\}/g, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/\\n/g, "\n")
    .replace(/\\t/g, "\t")
    .replace(/\\(["\\])/g, "$1");
}

const blocks = hashBlocks(ruby);

const wanted = [
  "SingularToPlural",
  "CamelToUnderscore",
  "CamelToUnderscoreWithoutReverse",
  "CamelWithModuleToUnderscoreWithSlash",
  "ClassNameToForeignKeyWithUnderscore",
  "ClassNameToForeignKeyWithoutUnderscore",
  "ClassNameToTableName",
  "UnderscoreToHuman",
  "UnderscoreToHumanWithoutCapitalize",
  "UnderscoreToHumanWithKeepIdSuffix",
  "MixtureToTitleCase",
  "MixtureToTitleCaseWithKeepIdSuffix",
  "StringToParameterized",
  "StringToParameterizedPreserveCase",
  "StringToParameterizeWithUnderscore",
  "UnderscoresToDashes",
  "OrdinalNumbers",
  "Irregularities",
];

const missing = wanted.filter((w) => !blocks.has(w));
if (missing.length > 0) {
  console.warn(`warning: fixtures not found in Rails source: ${missing.join(", ")}`);
}

const lit = (s: string) => JSON.stringify(s);

let ts = `// GENERATED by tools/port-fixtures.ts — do not edit by hand.
//
// Ported verbatim from Rails' activesupport/test/inflector_test_cases.rb.
// These are Rails' own test cases: passing them is what "parity" means here.
//
// Regenerate:  bun run port:fixtures

export type Pairs = readonly (readonly [string, string])[];

`;

let total = 0;
for (const name of wanted) {
  const pairs = blocks.get(name);
  if (!pairs) continue;
  total += pairs.length;
  const key = name.charAt(0).toLowerCase() + name.slice(1);
  ts += `/** ${pairs.length} cases from Rails \`${name}\`. */\n`;
  ts += `export const ${key}: Pairs = [\n`;
  for (const [a, b] of pairs) ts += `  [${lit(a)}, ${lit(b)}],\n`;
  ts += `];\n\n`;
}

ts += `/** Total ported cases: ${total}. */\nexport const portedCaseCount = ${total};\n`;

const dest = join(
  process.cwd(),
  "packages",
  "support",
  "test",
  "fixtures",
  "inflector-cases.ts",
);
writeFileSync(dest, ts);

console.log(`ported ${total} cases across ${wanted.length - missing.length} fixture groups`);
console.log(`wrote ${dest}`);
